### ISSUE TITLE
Converting the original dicom images to png

### ISSUE THREAD

**Issue by IssamLaradji** [DengPingFan/Inf-Net#12]
How did you convert the original images from [1] to png?
Thanks!
[1] https://medicalsegmentation.com/covid19/

**Comment by supergengchen** [comment]
Hi there, you can try to use python packages, e.g., nibabel, simpleITK, to read the NIfTI file, extract each slice, and then store the slice in PNG using opencv-python. Please refer to the following links for the details.

https://medium.com/@hbjenssen/covid-19-radiology-data-collection-and-preparation-for-artificial-intelligence-4ecece97bb5b
https://nipy.org/nibabel/
https://nifti.nimh.nih.gov/
https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_tutorials.html

**Comment by GewelsJI** [comment]
@supergengchen nice 👍
