### ISSUE TITLE
problems with configuring environment 

### ISSUE THREAD

**Issue by Yufengevan** [DengPingFan/Inf-Net#16]
When i  execute code:  pip install -r requirements.txt, it occurs the problem:
ERROR: Could not find a version that satisfies the requirement channelnorm-cuda==0.0.0 (from -r requirements.txt (line 3)) (from versions: none)
ERROR: No matching distribution found for channelnorm-cuda==0.0.0 (from -r requirements.txt (line 3))

How can i install this package?  Thank you for your replying.

**Comment by DengPingFan** [comment]
Hi, I think you may need to check your Cuda version.  There are many tutorials on the web.  There  are some solutions that may be useful for you: https://github.com/pytorch/pytorch/issues/10443

**Comment by tsaiwentage** [comment]
hi, did you solve the problem? I met the same problem with you

**Comment by Yufengevan** [comment]
Sorry, I just saw your reply. I have removed the packages that have error information, then run the: pip install -r  requirements.txt

**Comment by tsaiwentage** [comment]
> Sorry, I just saw your reply. I have removed the packages that have error information, then run the: pip install -r requirements.txt

ok, thanks!

**Comment by jibikbam** [comment]
This is still an issue!! @DengPingFan can you please update the requirements.txt or provide instructions?

**Comment by GewelsJI** [comment]
Hi, @jibikbam 

I modify the requirements.txt. Indeed, this repo can run on your custom environment, but you must meet the following three requirements (refer to [here](https://github.com/DengPingFan/Inf-Net/blob/master/requirements.txt)).


Best regards,
Ge-Peng.
