### ISSUE TITLE
Semi-Inf-Net + Multi-class UNet 提问

### ISSUE THREAD

**Issue by zhanglei1025** [DengPingFan/Inf-Net#17]
作者您好，我使用了第三个（Semi-Inf-Net + Multi-class UNet），训练完模型后使用了48张图片的测试集，但为什么class_12文件中的结果为（黄色为背景，绿色为团结，深红色为GGO），而且Consolidation与Ground-glass opacities文件中的图片为纯黑。
最后，我不太懂为什么测试代码中也有三个数据路径。那如何使用自己的数据进行预测呢？我只有肺窗的原图和切割好的肺实质，没有感染部分的标注。
期待您的答复，谢谢

**Comment by DengPingFan** [comment]
hi, 
Very sorry for the late response. The class_12 means we combine the class1 and class2 as the object-level class12.
Also, note that we save the image with an index value, thus, maybe you see consolidation and ground-glass opacities are black.
If you have any further questions, please send an email (dengpfan@gmail.com) to me and I will send you my WeChat so that we can contact real-time.

Best,

**Comment by zhanglei1025** [comment]
作者您好，我没能成功添加到您的微信，请您加我好吗。万分感谢！
15002344345




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DengPingFan/Inf-Net"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月2日(星期天) 晚上11:36
收件人:&nbsp;"DengPingFan/Inf-Net"<Inf-Net@noreply.github.com&gt;;
抄送:&nbsp;"root"<1823091488@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DengPingFan/Inf-Net] Semi-Inf-Net + Multi-class UNet 提问 (#17)





 
Closed #17.

**Comment by DengPingFan** [comment]
已经加你为好友了。通过一下就可以了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DengPingFan/Inf-Net"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月3日(星期一) 下午3:46
收件人:&nbsp;"DengPingFan/Inf-Net"<Inf-Net@noreply.github.com&gt;;
抄送:&nbsp;"Deng-Ping Fan"<381620505@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [DengPingFan/Inf-Net] Semi-Inf-Net + Multi-class UNet 提问 (#17)





 作者您好，我没能成功添加到您的微信，请您加我好吗。万分感谢！ 
 15002344345 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "DengPingFan/Inf-Net"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年8月2日(星期天) 晚上11:36 
 收件人:&amp;nbsp;"DengPingFan/Inf-Net"<Inf-Net@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"root"<1823091488@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [DengPingFan/Inf-Net] Semi-Inf-Net + Multi-class UNet 提问 (#17) 
 
 
 
 
 
   
 Closed #17.
