### ISSUE TITLE
Semi-Inf-Net

### ISSUE THREAD

**Issue by zhanglei1025** [DengPingFan/Inf-Net#18]
作者您好，我在使用第一个网络(inf-Net)测试时和第二个网络（Semi-Inf-Net）训练标签集时，均会遇到以下错误。
[Errno 2] No such file or directory: '/media/nercms/NERCMS/GepengJi/COVID-19/Code/PraNetPlusPlus/snapshots/res2net50_v1b_26w_4s-3cf99910.pth'
我只知道这个路径来自于Res2Net.py文件中，却不知道如何解决。期待您的回复，非常感谢！

**Comment by DengPingFan** [comment]
你检查一下这个路径是否存在，或者文件是否存在。/media/nercms/NERCMS/GepengJi/COVID-19/Code/PraNetPlusPlus/snapshots/res2net50_v1b_26w_4s-3cf99910.pth

**Comment by DengPingFan** [comment]
> 作者您好，我在使用第一个网络(inf-Net)测试时和第二个网络（Semi-Inf-Net）训练标签集时，均会遇到以下错误。
> [Errno 2] No such file or directory: '/media/nercms/NERCMS/GepengJi/COVID-19/Code/PraNetPlusPlus/snapshots/res2net50_v1b_26w_4s-3cf99910.pth'
> 我只知道这个路径来自于Res2Net.py文件中，却不知道如何解决。期待您的回复，非常感谢！

你发邮件给我，我把微信发给你。
