### ISSUE TITLE
The order of the paragraphs of "2.2.2. Usage " in README.md is wrong?

### ISSUE THREAD

**Issue by AManHasNoName12138** [DengPingFan/Inf-Net#19]
In "3.Train" section, the first paragraph should be before the fourth paragraph. Inf-Net_pseudo_100.pth is not obtained from "2.Generating Pseudo Labels (Optional)"， is it?

**Comment by DengPingFan** [comment]
> In "3.Train" section, the first paragraph should be before the fourth paragraph. Inf-Net_pseudo_100.pth is not obtained from "2.Generating Pseudo Labels (Optional)"， is it?

Q:  In "3.Train" section, the first paragraph should be before the fourth paragraph.
A: You are right! Thanks. We have updated the readme.

Q: Inf-Net_pseudo_100.pth is not obtained from "2.Generating Pseudo Labels (Optional)"， is it?
A: Yes, We have corrected it.
