### ISSUE TITLE
Ask about the reverse attention module

### ISSUE THREAD

**Issue by tantanhui** [DengPingFan/Inf-Net#21]
The author writes in the article that A (high-level feature maps) first concatenate B (edge-attention) and then multiply C (expand) in every reverse attention module, but the code shows that A first multiply C and then concatenate B. Which one is the author trying to express?

**Comment by DengPingFan** [comment]
> The author writes in the article that A (high-level feature maps) first concatenate B (edge-attention) and then multiply C (expand) in every reverse attention module, but the code shows that A first multiply C and then concatenate B. Which one is the author trying to express?

Yes, you are right, R = C (f * A, Dow(e_{att})). We will update the formulation accordingly. Thank you very much.

**Comment by tantanhui** [comment]
There's an error here.
[2020/08/15] Updateing the equation (2) in our manuscript.
R_i = C(f_i, Dow(e_att)) * A_i -> R_i = C(f_i, Dow(e_att)) * A_i;

**Comment by DengPingFan** [comment]
> There's an error here.
> [2020/08/15] Updateing the equation (2) in our manuscript.
> R_i = C(f_i, Dow(e_att)) * A_i -> R_i = C(f_i, Dow(e_att)) * A_i;

Thanks. It has been fixed.

**Comment by tantanhui** [comment]
thank you very much!

**Comment by 1215232494** [comment]
Figure 4 also needs to be modified accordingly.
