### ISSUE TITLE
About preprocess

### ISSUE THREAD

**Issue by ghost** [DengPingFan/Inf-Net#22]
Hello, thank you for your code. I still want to know what preprocessing you have done to the data? Because when running with my data, the result is not ideal. I would like to know if this is because of the difference in preprocessing or the data is too different?

**Comment by DengPingFan** [comment]
> the result is not ideal. I would like to know if this is because of the difference in preprocessing or the data is t

Hi, Actually, we didn't do special preprocessing. Maybe your problem is different. You can add my WeChat (You can Email me to obtain my wechat, dengpfan@gmail.com) for real-time communication.
