### ISSUE TITLE
A Question about Fig.3 in the paper

### ISSUE THREAD

**Issue by wbilife** [DengPingFan/Inf-Net#23]
您好，源码中Parallel Partial Decoder部分的实现，只有最后卷积核的大小是1*1，其他的都是3*3，按照我的理解，这和论文图3中两种卷积核的标注似乎是相反的，如果我的理解有错误，恳请纠正
![image](https://user-images.githubusercontent.com/59435866/95934477-7bd24280-0e03-11eb-8ebb-6119043c4370.png)
![image](https://user-images.githubusercontent.com/59435866/95934492-855baa80-0e03-11eb-9f7c-fcf67b7e38f5.png)

**Comment by GewelsJI** [comment]
Hi, 

You are right. Thanks for pointing out this issue and this issue may be incurring unnecessary misunderstanding. We will update accordingly. 

Best,
Ge-Peng Ji
