### ISSUE TITLE
generating pseudo-label images

### ISSUE THREAD

**Issue by SoUHoo** [DengPingFan/Inf-Net#24]
When generating pseudo-label images, a problem arises.

PseudoGenerator.py line 149, in inference_module
image, gt, name = test_loader.load_data()
ValueError: not enough values to unpack (expected 3, got 2)

I noticed that line 143 in the code says FIXME, so can the author tell me the specific implementation details

**Comment by GewelsJI** [comment]
Hi, @SoUHoo 

Sorry for the late reply.

I solved this bug. Please refer to this [line](https://github.com/DengPingFan/Inf-Net/blob/b2a4de7f27d9a0ccd508dbdb20f7724a7cb0b625/PseudoGenerator.py#L149).

Best regards,
Ge-Peng.
