### ISSUE TITLE
python evaluate toolbox

### ISSUE THREAD

**Issue by lonezhizi** [DengPingFan/Inf-Net#25]
Hi, very excellent work. Thanks for the code, it's very helpful and instructive! Howerve, i have a little request, could you provide a python evaluate toolbox. I dont install the matlab.
Best!

**Comment by DengPingFan** [comment]
Hi, 
There are two related toolboxes: 
https://github.com/zzhanghub/eval-co-sod
https://github.com/lartpang/PySODMetrics

**Comment by lonezhizi** [comment]
Thanks for sharing!
