### ISSUE TITLE
PraNetPlusPlus

### ISSUE THREAD

**Issue by Mitra-coding** [DengPingFan/Inf-Net#27]
Hi. Thanks for your sharing.
When I run "InfNet_VGGNet.py", I get this error:

"NameError: name 'PraNetPlusPlus' is not defined."

when I search into the script, there is just one line that 'PraNetPlusPlus' exists:

ras = PraNetPlusPlus().cuda()

Could you help me that how I can fix this?

**Comment by GewelsJI** [comment]
Hi, @SajedeMahla 

I check the code in this [file](https://github.com/DengPingFan/Inf-Net/blob/f74ce97623fa488d151428afe707f3e4acb7e5d5/Code/model_lung_infection/InfNet_VGGNet.py)

This line (`ras = PraNetPlusPlus().cuda()`) is used to debug. So it is deprecated and you can just delete it.

Thank you for your attention. Hope you have a nice day.

Best regards,
Ge-Peng.
