### ISSUE TITLE
请问Dice等计算函数应该在哪里加呢？

### ISSUE THREAD

**Issue by lmqMM** [DengPingFan/Inf-Net#32]
我前面在backword的后面加dice的计算,Dice_coeff(lateral_edge, gts)计算出来的数值很低，请问是什么原因呢？

**Comment by GewelsJI** [comment]
网络训练初期值偏低属于正常现象，另外请确保dice coeff函数的正确性，最后可以考虑调节一下多损失函数之间的占比权值

**Comment by lmqMM** [comment]
所以我取lateral_edge来做input，并与gts进行dice计算是正确的吧？我看了作者的论文有考虑过用lateral_map2来做input，但是结果值也还是低。麻烦作者帮忙看一下呢

**Comment by GewelsJI** [comment]
抱歉，我没有具体深入你的实验过程中，不能给出很准确的参考建议。不过你按照原始模型进行一些小的改动，一点一点的来改进自己的模型，对应的参数也要进行调节，这样会比较靠谱

**Comment by lmqMM** [comment]
好的，非常感谢你的回复！！
