### ISSUE TITLE
About the onehot.py

### ISSUE THREAD

**Issue by 1215232494** [DengPingFan/Inf-Net#33]
[onehot.py](https://github.com/DengPingFan/Inf-Net/blob/master/Code/utils/onehot.py)

def onehot(data, n):
    """onehot ecoder""" 
    buf = np.zeros(data.shape + (n,))
    nmsk = np.arange(data.size) * n + data.ravel()  
    buf.ravel()[nmsk - 1] = 1
    return buf

> When I run

label = np.asarray([[0,1,1], [0,0,2]])
print(label)
print("-----------")
label_onehot = onehot(label,3)
print(label_onehot.transpose(2, 0, 1))

> and get the following results:

[[0 1 1]
 [0 0 2]]
\-----------
[[[0 1 1]
  [0 0 0]]

 [[0 0 0]
  [0 0 1]]

 [[0 0 1]
  [1 0 1]]]

> This is not the correct result. The correct result should be as follows:

[[0 1 1]
 [0 0 2]]
\-----------
[[[1 0 0]
  [1 1 0]]

 [[0 1 1]
  [0 0 0]]

 [[0 0 0]
  [0 0 1]]]

> Is there an error in the code itself, or is there something wrong with me?

**Comment by GewelsJI** [comment]
Please provide more details of your experiments.
