### ISSUE TITLE
About the dataloader

### ISSUE THREAD

**Issue by 1215232494** [DengPingFan/Inf-Net#35]
[line](https://github.com/DengPingFan/Inf-Net/blob/02241f22099e0178e946ef84d26fd1fa97938060/Code/utils/dataloader_LungInf.py#L64)
if img.size == gt.size

> This condition filters out Pseudo labels. No pseudo labels can be read when generating pseudo labels or training with pseudo labels. Do I need to remove this condition?

**Comment by GewelsJI** [comment]
Please make sure that the shape of pseduo label is same as the shape of image. And then, the dataloader would not filter out the pseudo labels.

**Comment by 1215232494** [comment]
Thank you for your reply. Does it mean that I need to further process the pseudo label dataset myself?Similar to this [issue](https://github.com/DengPingFan/Inf-Net/issues/31#issuecomment-1156037179)

**Comment by GewelsJI** [comment]
You need to resize them but not to crop them.

**Comment by 1215232494** [comment]
got it，thanks！It means that I can get the same effect by removing the if statement
