### ISSUE TITLE
About the generation of picture edges

### ISSUE THREAD

**Issue by ZZ0214** [DengPingFan/Inf-Net#39]
Hello author, in the data set file you gave, there is an edge file that is not available in the official website. I would like to ask how these images with image boundary information are generated, thank you

**Comment by ZZ0214** [comment]
![image](https://user-images.githubusercontent.com/102795875/226785093-0f8be821-d3e8-4499-a8ba-86e480117d27.png)

**Comment by GewelsJI** [comment]
You can just refer to this code sample: https://github.com/JXingZhao/EGNet/blob/master/sal2edge.m
