### ISSUE TITLE
Pre trained data

### ISSUE THREAD

**Issue by GiulioBen** [DengPingFan/Inf-Net#4]
Dear Deng Ping Fan,

 I'm really interested in the model, however I cannot find the pre-trained weights..

Could you kindly check the links in the intructions? 

Best

Giulio

**Comment by GewelsJI** [comment]
@GiulioBen Thank you for your attention. Today, I will update all the google drive links that are appeared in our implementation.

---- 2020/05/14 ----
I have uploaded all the dataset, train/test code and pre-trained weights. If you have other questions, please feel free to contact me, enjoy it!
