### ISSUE TITLE
download data

### ISSUE THREAD

**Issue by Yufengevan** [DengPingFan/Inf-Net#9]
Thank you for your sharing.
I can't download the data that you uploaded in GoogleDrive due to can't connect google.
Could you give an another download link such as BaiDuYunPan of the data sets and pretrained weightes? 
Thanks again.

**Comment by DengPingFan** [comment]
We will update a new link today. Please check them late. As an alternative scheme, you need a VPN to connect Google Drive.

**Comment by GewelsJI** [comment]
@Yufengevan You can download the test/train data in this [section](https://github.com/DengPingFan/Inf-Net#4-covid-semiseg-dataset). I will borrow all the necessary data into Baidu Drive for convenience. Thank you for your attention. Have a nice day!

**Comment by Yufengevan** [comment]
OK! Thank you for your prompt reply!
